<?php

namespace Tests\Unit\Model;

use App\Model\Category;
use App\Model\Product;
use Illuminate\Database\Eloquent\Collection;
use Tests\TestCase;

class CategoryTest extends TestCase
{
    protected $category;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->category = Category::firstOrCreate(['name' => 'Testing'], [
            'name' => 'Testing',
            'parent_id' => null,
        ]);
    }

    public function test_contains_valid_fillable_properties()
    {
        $this->assertEquals([
            'name',
            'parent_id',
        ], $this->category->getFillable());
    }

    public function test_category_has_many_products()
    {
        $category = $this->category;

        $product = Product::firstOrCreate(['category_id' => $category->id], [
            'name' => 'Testing',
            'price' => 1234,
            'category_id' => $category->id,
        ]);

        $this->assertTrue($category->products->contains($product));
        $this->assertInstanceOf(Collection::class, $category->products);
    }
}
