<?php

namespace Tests\Unit\Model;

use App\Model\Comment;
use App\Model\Product;
use App\Model\User;
use Tests\TestCase;

class CommentTest extends TestCase
{
    protected $comment;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->comment = Comment::firstOrCreate(['comment' => 'Testing'], [
            'comment' => 'Testing',
            'user_id' => 1,
            'product_id' => 1,
        ]);
    }

    public function test_contains_valid_fillable_properties()
    {
        $this->assertEquals([
            'comment',
            'user_id',
            'product_id',
        ], $this->comment->getFillable());
    }

    public function test_comment_belong_to_product()
    {
        $comment = $this->comment;

        $this->assertInstanceOf(Product::class, $comment->product);
    }

    public function test_comment_belong_to_user()
    {
        $comment = $this->comment;

        $this->assertInstanceOf(User::class, $comment->user);
    }
}
