<?php

namespace Tests\Unit\Model;

use App\Model\Order;
use App\Model\OrderDetail;
use Illuminate\Database\Eloquent\Collection;
use Tests\TestCase;

class OrderDetailTest extends TestCase
{
    protected $orderDetail;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->orderDetail = OrderDetail::firstOrCreate(['order_id' => 1], [
            'order_id' => 1,
            'product_id' => 1,
            'quantity' => 1,
            'unit_price' => 1234,
        ]);
    }

    public function test_contains_valid_fillable_properties()
    {
        $orderDetail = $this->orderDetail;

        $this->assertEquals([
            'order_id',
            'product_id',
            'quantity',
            'unit_price',
        ], $orderDetail->getFillable());
    }

    public function test_order_detail_belong_to_order()
    {
        $orderDetail = $this->orderDetail;

        $this->assertInstanceOf(Order::class, $orderDetail->order);
    }

    public function test_order_detail_belong_to_many_products()
    {
        $orderDetail = $this->orderDetail;

        $this->assertInstanceOf(Collection::class, $orderDetail->products);
    }
}
