<?php

namespace Tests\Unit\Model;

use App\Model\Product;
use App\Model\ProductImage;
use Tests\TestCase;

class ProductImageTest extends TestCase
{
    protected $productImage;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->productImage = ProductImage::firstOrCreate(['image_path' => 'Testing'], [
            'image_path' => 'Testing',
            'image_type' => 1,
            'product_id' => 1,
        ]);
    }

    public function test_contains_valid_fillable_properties()
    {
        $productImage = $this->productImage;

        $this->assertEquals([
            'image_path',
            'image_type',
            'product_id',
        ], $productImage->getFillable());
    }

    public function test_product_image_belong_to_product()
    {
        $productImage = $this->productImage;

        $this->assertInstanceOf(Product::class, $productImage->product);
    }
}
