<?php

namespace Tests\Unit\Model;

use App\Model\Rating;
use App\Model\User;
use Illuminate\Database\Eloquent\Collection;
use Tests\TestCase;

class RatingTest extends TestCase
{
    protected $rating;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->rating = Rating::firstOrCreate(['user_id' => 1], [
            'user_id' => 1,
            'product_id' => 1,
            'rated_index' => 1,
        ]);
    }

    public function test_contains_valid_fillable_properties()
    {
        $rating = $this->rating;

        $this->assertEquals([
            'rated_index',
            'user_id',
            'product_id',
        ], $rating->getFillable());
    }

    public function test_rating_belong_to_user()
    {
        $rating = $this->rating;

        $this->assertInstanceOf(User::class, $rating->user);
    }

    public function test_rating_belong_to_many_products()
    {
        $rating = $this->rating;

        $this->assertInstanceOf(Collection::class, $rating->products);
    }
}
